services:
  backend:
    container_name: backend
    build: ./Server
    volumes:
      - ./cert.pem:/app/cert.pem
      - ./key.pem:/app/key.pem
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    environment:
      - VITE_DEPLOYMENT_TYPE="remote"
      - VITE_CLIENT_PORT=443
      - VITE_SERVER_PORT=3000
      - VITE_CLIENT_ID="3g1kiuq5c9n7hkpjc0m59h1dd6"
  frontend:
    container_name: frontend
    build: ./Client
    volumes:
      - ./cert.pem:/etc/nginx/certs/ssl_certificate.crt
      - ./key.pem:/etc/nginx/certs/ssl_certificate.key
    environment:
      - VITE_DEPLOYMENT_TYPE="remote"
      - VITE_CLIENT_PORT=443
      - VITE_SERVER_PORT=3000
      - VITE_CLIENT_ID="3g1kiuq5c9n7hkpjc0m59h1dd6"
    ports:
      - "443:443"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
