services:
  backend:
    container_name: backend
    build: ./Server
    volumes:
      - ./cert.pem:/app/cert.pem
      - ./key.pem:/app/key.pem
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    environment:
      - VITE_DEPLOYMENT_TYPE=${VITE_DEPLOYMENT_TYPE}
      - VITE_CLIENT_PORT=${VITE_CLIENT_PORT}
      - VITE_CLIENT_ID=${VITE_CLIENT_ID}
    env_file:
      - path: .env
  frontend:
    container_name: frontend
    build: ./Client
    volumes:
      - ./cert.pem:/etc/nginx/certs/ssl_certificate.crt
      - ./key.pem:/etc/nginx/certs/ssl_certificate.key
    environment:
      - VITE_SERVER_PORT=${VITE_SERVER_PORT}
      - VITE_CLIENT_ID=${VITE_CLIENT_ID}
    ports:
      - "443:443"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
