---
- hosts: app
  become: true
  tasks:
    - name: Install necessary dependencies
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        
    - name: Add GPG keys
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        
    - name: Add Docker repo
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present
        
    - name: Install docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        
    - name: Check if Docker service is active
      service:
        name: docker
        state: started
        enabled: yes
        
    - name: Clone git repo
      git:
        repo: https://github.com/wdomini4801/cloud-solutions-in-web-appliactions.git
        dest: /home/cloud
        clone: yes
        update: yes
        version: one-ec2
        
    - name: Write .env file
      copy:
        content: |
          VITE_DEPLOYMENT_TYPE="remote"
          VITE_CLIENT_PORT=443
          VITE_SERVER_PORT=3000
          VITE_CLIENT_ID="3g1kiuq5c9n7hkpjc0m59h1dd6"
        dest: /home/cloud/.env
        
    - name: Write .env file for client
      copy:
        content: |
          VITE_DEPLOYMENT_TYPE="remote"
          VITE_CLIENT_PORT=443
          VITE_SERVER_PORT=3000
          VITE_CLIENT_ID="3g1kiuq5c9n7hkpjc0m59h1dd6"
        dest: /home/cloud/Client/.env
        
    - name: Copy cert.pem
      copy:
        src: ~/environment/cert.pem
        dest: /home/cloud/cert.pem
        owner: ubuntu
        group: ubuntu
        mode: '0400'
        
    - name: Copy key.pem
      copy:
        src: ~/environment/key.pem
        dest: /home/cloud/key.pem
        owner: ubuntu
        group: ubuntu
        mode: '0400'
        
    - name: Start app
      command: docker compose up -d
      args:
        chdir: /home/cloud
        